# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('browse', models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf')),
                ('status', models.IntegerField(default=0, verbose_name='\u6587\u7ae0\u72b6\u6001\uff0c0\uff1a\u5b58\u5728\uff0c1\uff1a\u5df2\u5220\u9664')),
                ('update_time', models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('parent_id', models.IntegerField(verbose_name='\u7236id')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u6807\u7b7e\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('password', models.CharField(max_length=30, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('update_time', models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1\u5730\u5740')),
                ('gender', models.IntegerField(verbose_name='\u6027\u522b')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.UserMessage', verbose_name='\u7528\u6237\u4fe1\u606fid'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='\u6587\u7ae0\u4f5c\u8005id'),
        ),
        migrations.AddField(
            model_name='article',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleClassify', verbose_name='\u5206\u7c7bid'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
